import type { CompanyDna, Recommendations } from './appTypes';

function download(filename: string, content: string, type = 'text/markdown') {
	const blob = new Blob([content], { type });
	const url = URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = filename;
	a.click();
	URL.revokeObjectURL(url);
}

function slug(s: string): string {
	return (s || 'company').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/* --------------------------- Markdown plan --------------------------- */
export function exportMarkdownPlan(dna: CompanyDna, recs: Recommendations) {
	const L: string[] = [];
	L.push(`# ${dna.companyName} - Marketing Plan`);
	L.push(`\n*${dna.oneLine}*\n`);
	L.push(`Built with Clario. Brand archetype: **${dna.archetype.name}**. ${dna.archetype.why}\n`);

	L.push(`## Company DNA\n`);
	L.push(`**Voice.** Register: ${dna.voice.register}. Cadence: ${dna.voice.cadence}. Vocabulary: ${dna.voice.vocabulary}. Humor: ${dna.voice.humor}.`);
	if (dna.voice.signaturePhrases?.length) L.push(`Signature phrases: ${dna.voice.signaturePhrases.join('; ')}.`);
	L.push(`\n**Identity.** ${dna.identity.mission} Value: ${dna.identity.valueProposition}. Audience: ${dna.identity.audience}.`);
	if (dna.identity.differentiators?.length) L.push(`Differentiators: ${dna.identity.differentiators.join('; ')}.`);
	L.push(`\n**Story.** Origin: ${dna.story.origin} The villain: ${dna.story.villain} Transformation: ${dna.story.transformation}`);
	L.push(`\n**Always:** ${dna.rules.always.join('; ')}.`);
	L.push(`**Never:** ${dna.rules.never.join('; ')}.\n`);

	if (recs.personas?.length) {
		L.push(`## Target audiences\n`);
		for (const p of recs.personas) {
			L.push(`### ${p.name}`);
			L.push(`${p.snapshot}`);
			L.push(`- Demographics: ${p.demographics}`);
			L.push(`- Psychographics: ${p.psychographics}`);
			L.push(`- Where they are: ${p.wateringHoles?.join(', ')}`);
			L.push(`- Message angle: ${p.messageAngle}\n`);
		}
	}

	L.push(`## Channel plan\n`);
	L.push(`> Estimates are honest ranges with assumptions, not guarantees. Forecasts are labeled. Validate with incrementality and holdout testing before reallocating budget.\n`);
	L.push(`| Channel | Fit | Budget | Est. ROI | KPIs | Angle |`);
	L.push(`| --- | --- | --- | --- | --- | --- |`);
	for (const c of recs.channels) {
		const star = c.isTopPick ? ' (top pick)' : '';
		L.push(
			`| ${c.name}${star} | ${c.fit} | ${Math.round(c.budgetPct)}% | ${c.roiRange} | ${c.kpis?.join(', ')} | ${c.messaging} |`
		);
	}

	L.push(`\n### Rationale by channel\n`);
	for (const c of recs.channels) {
		L.push(`**${c.name}.** ${c.rationale} Success: ${c.successRange}\n`);
	}

	if (recs.budget) {
		L.push(`## Budget\n`);
		L.push(recs.budget.total ? `Total: ${recs.budget.total} ${recs.budget.currency}.` : `Allocations are percentages of total spend.`);
		L.push(`${recs.budget.notes}\n`);
	}

	L.push(`---\n`);
	L.push(`*Generated by Clario. Every customer-facing asset is written in ${dna.companyName}'s Company DNA and scored for authenticity so it reads human, not AI.*`);

	download(`${slug(dna.companyName)}-marketing-plan.md`, L.join('\n'));
}

/* ------------------------------ Deck -------------------------------- */
export async function exportDeck(dna: CompanyDna, recs: Recommendations) {
	const pptxgen = (await import('pptxgenjs')).default;
	const pptx = new pptxgen();
	pptx.defineLayout({ name: 'WIDE', width: 13.333, height: 7.5 });
	pptx.layout = 'WIDE';

	const PAPER = 'F6F2E9';
	const INK = '1B1712';
	const SOFT = '4B4239';
	const ACCENT = 'C8492B';
	const MUTED = '857A6A';

	const eyebrow = (t: string) => ({ text: t, options: { color: ACCENT, fontFace: 'Courier New', fontSize: 11, charSpacing: 2 } });

	// 1. Title
	let s = pptx.addSlide();
	s.background = { color: PAPER };
	s.addText('COMPANY DNA', { x: 0.7, y: 0.7, color: ACCENT, fontFace: 'Courier New', fontSize: 12, charSpacing: 3 });
	s.addText(dna.companyName, { x: 0.65, y: 1.4, w: 12, h: 1.6, color: INK, fontFace: 'Georgia', fontSize: 54, bold: false });
	s.addText(dna.oneLine, { x: 0.7, y: 3.0, w: 11, h: 1, color: SOFT, fontFace: 'Georgia', italic: true, fontSize: 22 });
	s.addText(`Archetype: ${dna.archetype.name}`, { x: 0.7, y: 4.2, color: ACCENT, fontSize: 16, bold: true });
	s.addText(recs.summary || '', { x: 0.7, y: 4.8, w: 11.5, h: 1.6, color: SOFT, fontSize: 14 });

	// 2. Voice
	s = pptx.addSlide();
	s.background = { color: PAPER };
	s.addText([eyebrow('01 / VOICE')], { x: 0.7, y: 0.6 });
	s.addText('How this brand sounds', { x: 0.65, y: 1.1, color: INK, fontFace: 'Georgia', fontSize: 34 });
	const voiceRows = [
		['Register', dna.voice.register],
		['Cadence', dna.voice.cadence],
		['Vocabulary', dna.voice.vocabulary],
		['Humor', dna.voice.humor]
	];
	s.addTable(
		voiceRows.map((r) => [
			{ text: r[0], options: { color: MUTED, fontFace: 'Courier New', fontSize: 12, bold: true } },
			{ text: r[1], options: { color: INK, fontSize: 14 } }
		]),
		{ x: 0.7, y: 2.1, w: 12, colW: [2.6, 9.4], border: { type: 'solid', color: 'E4DCCA', pt: 1 }, rowH: 0.7 }
	);

	// 3. Story
	s = pptx.addSlide();
	s.background = { color: PAPER };
	s.addText([eyebrow('02 / STORY')], { x: 0.7, y: 0.6 });
	s.addText('The story we tell', { x: 0.65, y: 1.1, color: INK, fontFace: 'Georgia', fontSize: 34 });
	const beats = [
		['Origin', dna.story.origin],
		['The villain', dna.story.villain],
		['Transformation', dna.story.transformation]
	];
	beats.forEach((b, i) => {
		s.addText(b[0], { x: 0.7, y: 2.1 + i * 1.55, color: ACCENT, fontFace: 'Courier New', fontSize: 12, bold: true });
		s.addText(b[1], { x: 0.7, y: 2.4 + i * 1.55, w: 11.8, h: 1.1, color: SOFT, fontSize: 15 });
	});

	// 4. Channel plan
	s = pptx.addSlide();
	s.background = { color: PAPER };
	s.addText([eyebrow('03 / CHANNEL PLAN')], { x: 0.7, y: 0.5 });
	s.addText('Where to invest', { x: 0.65, y: 0.95, color: INK, fontFace: 'Georgia', fontSize: 30 });
	const header = ['Channel', 'Fit', 'Budget', 'Est. ROI', 'KPIs'].map((h) => ({
		text: h,
		options: { color: PAPER, fill: { color: INK }, bold: true, fontSize: 11, fontFace: 'Courier New' }
	}));
	const rows = recs.channels.slice(0, 12).map((c) => [
		{ text: c.name + (c.isTopPick ? '  *' : ''), options: { color: INK, fontSize: 11, bold: c.isTopPick } },
		{ text: c.fit, options: { color: SOFT, fontSize: 11 } },
		{ text: `${Math.round(c.budgetPct)}%`, options: { color: ACCENT, fontSize: 11, bold: true } },
		{ text: c.roiRange, options: { color: SOFT, fontSize: 9 } },
		{ text: (c.kpis || []).slice(0, 3).join(', '), options: { color: SOFT, fontSize: 9 } }
	]);
	s.addTable([header, ...rows], {
		x: 0.6,
		y: 1.6,
		w: 12.1,
		colW: [3.2, 1.1, 1.2, 3.6, 3.0],
		border: { type: 'solid', color: 'E4DCCA', pt: 1 },
		valign: 'middle'
	});
	s.addText('* top pick. Ranges are directional with assumptions, not guarantees. Validate with incrementality testing.', {
		x: 0.6,
		y: 6.9,
		color: MUTED,
		fontSize: 10,
		italic: true
	});

	// 5. Close
	s = pptx.addSlide();
	s.background = { color: INK };
	s.addText('Marketing that sounds human,', { x: 0.7, y: 2.6, w: 12, color: PAPER, fontFace: 'Georgia', fontSize: 40 });
	s.addText('not like AI.', { x: 0.7, y: 3.5, w: 12, color: ACCENT, fontFace: 'Georgia', fontSize: 40 });
	s.addText('Every asset written in your Company DNA and scored for authenticity. Built with Clario.', {
		x: 0.7,
		y: 4.7,
		w: 11,
		color: 'C9BFAE',
		fontSize: 15
	});

	await pptx.writeFile({ fileName: `${slug(dna.companyName)}-clario-deck.pptx` });
}
